
# Config file for automatic testing at travis-ci.org

language: python
python:

  - "3.6"
  - "3.7"
  - "3.8"
# os:
#   - linux
#   - osx


install:
  - pip install --upgrade pytest-cov codecov
  - python setup.py install
script:
  - python -m pytest -vv   --cov=yaml_config/
  - codecov --token=1c460da4-be1e-432a-9ebf-84bf5247e486









